#Use the new container-based infrastructure
sudo: false
language: sourcepawn

#Install some apt packages needed for spcomp
addons:
  apt_packages:
    - lib32stdc++6
    
matrix:
  allow_failures:
    - env: SOURCEMOD=1.11

#Set the build environment
env:
  - SOURCEMOD=1.9
  - SOURCEMOD=1.10
  - SOURCEMOD=1.11

#And compile!
before_script:
  - wget "http://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O game/sourcemod-$SOURCEMOD-linux.tar.gz
  - cd game
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - cd addons/sourcemod/scripting/
  - wget https://raw.githubusercontent.com/sbpp/Updater-include-mirror/master/scripting/include/updater.inc -O include/updater.inc
  - chmod +x spcomp

script:
  - ./spcomp sbpp_main.sp -E -i$PWD -v0
  - ./spcomp sbpp_admcfg.sp -E -i$PWD -v0
  - ./spcomp sbpp_comms.sp -E -i$PWD -v0
  - ./spcomp sbpp_checker.sp -E -i$PWD -v0
  - ./spcomp sbpp_sleuth.sp -E -i$PWD -v0
  - ./spcomp sbpp_report.sp -E -i$PWD -v0
